[package]
name = "grpc-api"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.1"
serde = { version = "1.0.228", features = ["derive"] }
tonic = "0.14.2"
tonic-prost = "0.14.2"

[build-dependencies]
tonic-prost-build = "0.14.2"
